version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - PORT=${WEB_PORT}
      - API_HOST=${API_HOST}
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - DB=${API_DB}
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devops_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
